#!/bin/sh
#
# setup-cron.sh -- Manage keaunbound cron jobs
#
# Reads the KeaUnbound configuration and sets up/removes cron.d entries
# for the auto-clean job based on enable_auto_clean and auto_clean_interval settings.
#
# Called from the GeneralController when settings are saved.

CRON_FILE="/usr/local/etc/cron.d/keaunbound"
CONFIG_FILE="/conf/config.xml"

# Read configuration using xmllint
read_config() {
    local xpath=$1
    xmllint --xpath "string(${xpath})" "$CONFIG_FILE" 2>/dev/null || echo ""
}

# Get settings
ENABLE_AUTO_CLEAN=$(read_config "//OPNsense/KeaUnbound/general/enable_auto_clean")
AUTO_CLEAN_INTERVAL=$(read_config "//OPNsense/KeaUnbound/general/auto_clean_interval")

# Default interval to 6 hours if not set
if [ -z "$AUTO_CLEAN_INTERVAL" ]; then
    AUTO_CLEAN_INTERVAL="6"
fi

# If auto-clean is disabled, remove the cron file
if [ "$ENABLE_AUTO_CLEAN" != "1" ]; then
    if [ -f "$CRON_FILE" ]; then
        rm -f "$CRON_FILE"
        logger -t keaunbound "Auto-clean cron job disabled"
    fi
    exit 0
fi

# Generate cron schedule based on interval
case "$AUTO_CLEAN_INTERVAL" in
    6)
        # Every 6 hours: 0, 6, 12, 18
        CRON_SCHEDULE="0 0,6,12,18 * * *"
        ;;
    12)
        # Every 12 hours: 0, 12
        CRON_SCHEDULE="0 0,12 * * *"
        ;;
    24)
        # Every 24 hours: 0 (midnight)
        CRON_SCHEDULE="0 0 * * *"
        ;;
    *)
        logger -t keaunbound "ERROR: Invalid auto_clean_interval: $AUTO_CLEAN_INTERVAL"
        exit 1
        ;;
esac

# Create or update the cron.d file
cat > "$CRON_FILE" << EOF
# KeaUnbound auto-clean job
# Generated by setup-cron.sh - do not edit manually
# Changes will be overwritten when KeaUnbound settings are saved

$CRON_SCHEDULE root /usr/local/opnsense/scripts/keaunbound/local-data-clean.py >> /var/log/keaunbound-clean.log 2>&1
EOF

# Ensure proper permissions
chmod 644 "$CRON_FILE"

logger -t keaunbound "Auto-clean cron job configured: interval ${AUTO_CLEAN_INTERVAL}h, schedule: $CRON_SCHEDULE"
exit 0
