[start]
command:/usr/local/opnsense/scripts/keaunbound/start.py
parameters:
type:script_output
message:starting kea-unbound-ddns
description:Kea Unbound DDNS

[stop]
command:/bin/pkill -F /var/run/kea-unbound-ddns.pid
parameters:
type:script_output
message:stopping kea-unbound-ddns
description:Kea Unbound DDNS

[restart]
command:/bin/pkill -F /var/run/kea-unbound-ddns.pid ; sleep 1 ; /usr/local/opnsense/scripts/keaunbound/start.py
parameters:
type:script_output
message:restarting kea-unbound-ddns
description:Kea Unbound DDNS

[status]
command:/bin/pgrep -F /var/run/kea-unbound-ddns.pid && echo running || echo stopped
parameters:
type:script_output
message:checking kea-unbound-ddns status
description:Kea Unbound DDNS
