[start]
command:/usr/local/opnsense/scripts/keaunbound/start.py
parameters:
type:script_output
message:starting kea-unbound-ddns
description:Kea Unbound DDNS

[stop]
command:/bin/pkill -F /var/run/kea-unbound-ddns.supervisor.pid ; /bin/rm -f /var/run/kea-unbound-ddns.supervisor.pid /var/run/kea-unbound-ddns.pid
parameters:
type:script_output
message:stopping kea-unbound-ddns
description:Kea Unbound DDNS

[restart]
command:/bin/pkill -F /var/run/kea-unbound-ddns.supervisor.pid ; /bin/rm -f /var/run/kea-unbound-ddns.supervisor.pid /var/run/kea-unbound-ddns.pid ; sleep 2 ; /usr/local/opnsense/scripts/keaunbound/start.py
parameters:
type:script_output
message:restarting kea-unbound-ddns
description:Kea Unbound DDNS

[status]
command:/usr/local/sbin/pluginctl -s kea-unbound-ddns status
parameters:
type:script_output
message:checking kea-unbound-ddns status
description:Kea Unbound DDNS

[sync_static]
command:/usr/local/opnsense/scripts/keaunbound/reservation-sync.py
parameters:
type:script
message:Syncing Kea static reservations to Unbound
description:Kea Unbound DDNS: sync static reservations

[sync_dynamic]
command:/usr/local/opnsense/scripts/keaunbound/lease-sync.py
parameters:
type:script
message:Syncing Kea active leases to Unbound
description:Kea Unbound DDNS: sync active leases

[clean]
command:/usr/local/opnsense/scripts/keaunbound/local-data-clean.py
parameters:
type:script
message:Cleaning stale DNS records from Unbound
description:Kea Unbound DDNS: clean stale DNS records
