[keaunbound.setup_cron]
command:/usr/local/opnsense/scripts/keaunbound/setup-cron.sh
parameters:
type:script
message:Setting up KeaUnbound cron jobs

[keaunbound.sync_static]
command:/usr/local/opnsense/scripts/keaunbound/reservation-sync.py
parameters:
type:script
message:Syncing Kea static reservations to Unbound

[keaunbound.sync_dynamic]
command:/usr/local/opnsense/scripts/keaunbound/lease-sync.py
parameters:
type:script
message:Syncing Kea active leases to Unbound

[keaunbound.clean]
command:/usr/local/opnsense/scripts/keaunbound/local-data-clean.py --confirm
parameters:
type:script
message:Cleaning stale DNS records from Unbound
